version: '3.9'

services:
  registry_proxy:
    image: registry
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  app:
    depends_on:
      - registry
    image: 127.0.0.1:5000/dzdd
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
